### ISSUE TITLE
TensorFlow not found for Python 2.7

### ISSUE THREAD

**Issue by Rich2006** [jjy1994/MemGuard#2]
Hello Jinyuan Jia, requirements that you stated for running your code are Python 2.7, Keras (2.2.2), TensorFlow 1.8.0. However, TensorFlow is currently supported for Python 3.5–3.8.

Is there anything that I am missing or do you have a way around that?
Thank you!

**Comment by jinyuan-jia** [comment]
Hi Rich2006,  I would suggest you trying with Python3.5 (or 3.6) and Tensorflow 1.14.0. Hope this helps.
