### ISSUE TITLE
How to obtain the npz files

### ISSUE THREAD

**Issue by Kruthikmanubolu** [jjy1994/MemGuard#4]
Dear Jinyuan Jia,

I hope this email finds you in good health and spirits.

I have been closely following your project, https://github.com/jinyuan-jia/MemGuard,  and greatly admire the work that has been done. The datasets provided on the GitHub repository (https://github.com/privacytrustlab/datasets), particularly dataset_location.tgz, have sparked my interest due to their relevance to my current research.

While exploring the datasets, I encountered a specific query regarding the extraction process of two files: data/location/data_complete.npz and data/location/shuffle_index.npz from the dataset_location.tgz archive. These files seem crucial for a comprehensive analysis, and I am keen on understanding the methodology or steps involved in retrieving or generating them from the compressed archive.

Could you kindly enlighten me on how these .npz files were derived from the dataset_location.tgz? Any details about tools, scripts, or commands employed in this process would be immensely helpful and appreciated.

Your guidance will significantly contribute to advancing my research and understanding of the dataset's structure and content. I am eager to delve deeper into the dataset, and resolving this doubt will greatly facilitate my endeavors.

Thank you very much for your time and consideration. I look forward to your valuable response.

Best regards,
Lakshman Kruthik Manubolu

**Comment by jinyuan-jia** [comment]
Hi,

Please check for the piece of code in my reply email.

Best,
Jinyuan

**Comment by tryIcatch** [comment]
Dear Jinyuan Jia,

I hope this email finds you in good health and spirits.

I came across your GitHub project on MemGuard (https://github.com/jinyuan-jia/MemGuard) and noticed the datasets you provided, particularly dataset_location.tgz. I have a question that aligns with a query raised by another user.

Specifically, I’m interested in how to extract or generate the files data/location/data_complete.npz and data/location/shuffle_index.npz from the dataset_location.tgz archive. Could you please share the steps or tools used in this process?

Your guidance would be greatly appreciated.

Best regards,
Haocheng Jiang

**Comment by tryIcatch** [comment]
Dear Jinyuan Jia,

I hope you are doing well.

I wanted to follow up on the email I sent earlier regarding the dataset in your MemGuard project. After further exploring your code, I realized that the solution to my question was actually included, and I missed it. I apologize for any inconvenience this may have caused.

Thank you for providing such detailed work. I appreciate your understanding.

Best regards,
Haocheng Jiang

**Comment by jinyuan-jia** [comment]
Sounds great. Thanks for letting me know. Best of luck with your research.
